import javax.swing.JOptionPane;
/*
 * pfcGuiGestor.java
 *
 * Created on 4 / desembre / 2007, 07:15
 */

/**
 *
 * @author  Gerard Farràs i Ballabriga <gfarrasb@uoc.edu>
 */
public class pfcGuiGestor extends javax.swing.JFrame {
    
    /** Creates new form pfcGuiGestor */
    public pfcGuiGestor() {
        initComponents();
        this.centraFormulari();
        servidorRmiIniciat = false;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        botoSurt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textPortRMI = new javax.swing.JTextField();
        textContrasenyaGestor = new javax.swing.JPasswordField();
        botoInicia = new javax.swing.JButton();
        botoAtura = new javax.swing.JButton();
        botoAfegeixPac = new javax.swing.JButton();
        botoAfegeixProf = new javax.swing.JButton();
        pathP12Gestor = new javax.swing.JTextField();
        botoCercaP12Gestor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PfcHistorials - Gestor");
        botoSurt.setText("Surt");
        botoSurt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoSurtActionPerformed(evt);
            }
        });

        jLabel4.setText("Port servidor RMI:");

        jLabel5.setText("P12 gestor");

        jLabel6.setText("Contrasenya P12:");

        botoInicia.setText("Inicia");
        botoInicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoIniciaActionPerformed(evt);
            }
        });

        botoAtura.setText("Atura");
	botoAtura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAturaActionPerformed(evt);
            }
        });

        botoAfegeixPac.setText("Afegeix Pacient");
        botoAfegeixPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAfegeixPacActionPerformed(evt);
            }
        });

        botoAfegeixProf.setText("Afegeix Professional");
	botoAfegeixProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAfegeixProfActionPerformed(evt);
            }
        });

        botoCercaP12Gestor.setText("Cerca");
        botoCercaP12Gestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoCercaP12GestorActionPerformed(evt);
            }
        });

        jLabel1.setText("Configuraci\u00f3 Gestor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botoInicia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botoAtura)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botoAfegeixPac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botoAfegeixProf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(botoSurt))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pathP12Gestor, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botoCercaP12Gestor))
                            .addComponent(textPortRMI, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textContrasenyaGestor, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textPortRMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pathP12Gestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botoCercaP12Gestor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textContrasenyaGestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botoAfegeixPac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoSurt)
                    .addComponent(botoInicia)
                    .addComponent(botoAtura)
                    .addComponent(botoAfegeixProf))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoAfegeixPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoAfegeixPacActionPerformed

	/*
        if ( this.servidorRmiIniciat == false ) {
            
            javax.swing.JOptionPane.showMessageDialog(null, "Error: El servidor RMI ha d'estar iniciat per a crear nous usuaris", "Error", JOptionPane.ERROR_MESSAGE);            
           
            
        } else {
	*/
            
            pfcGuiGestorNewPacient pfcGuiGestorNewPacient = new pfcGuiGestorNewPacient();
            pfcGuiGestorNewPacient.estableixDades ( this );        
            pfcGuiGestorNewPacient.setVisible(true);    
        /*
        }*/
        
        
        
        
    }//GEN-LAST:event_botoAfegeixPacActionPerformed

    private void botoCercaP12GestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoCercaP12GestorActionPerformed
// TODO add your handling code here:
        
         javax.swing.JFileChooser a = new javax.swing.JFileChooser();      
         a.setVisible(true);         
        
       
        int returnVal = a.showOpenDialog(this);        
    
        if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {            
            
               pathP12Gestor.setText(a.getSelectedFile().getAbsolutePath());               
            
            //textUsuari.setText( a.getSelectedFile().getAbsolutePath());
            //this.nomUsuari = a.getSelectedFile().getName().substring(0, a.getSelectedFile().getName().indexOf("."));                       
            
        }
        
        
    }//GEN-LAST:event_botoCercaP12GestorActionPerformed

	private void botoAfegeixProfActionPerformed( java.awt.event.ActionEvent evt ) {
		
		javax.swing.JOptionPane.showMessageDialog ( null, "Funcionalitat NO implementada! Disculpeu les molesties!",  
							    "Error", javax.swing.JOptionPane.ERROR_MESSAGE ); 
	}

     void centraFormulari () {
        
        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        java.awt.Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;                
        setLocation(screenWidth / 4, screenHeight / 4);
        
    }

	private void botoAturaActionPerformed( java.awt.event.ActionEvent evt) {
		
		if (this.servidorRmiIniciat == true) {

			aturaServeiRmi();

		} else {

			javax.swing.JOptionPane.showMessageDialog ( null, "El servidor RMI GestorRMI NO està iniciat", "Informació", javax.swing.JOptionPane.INFORMATION_MESSAGE );

		}
	}

	/**
	*	Aquest mètode atura el servidor de RMI
	* 
	*/
	private void aturaServeiRmi () {		

		try {

		String a = new String ( "//" + java.net.InetAddress.getLocalHost().getHostAddress() +  ":" + textPortRMI.getText() + "/GestorRMI");
		java.rmi.Naming.unbind ( a );

		} catch ( java.net.MalformedURLException io ) {

			System.out.println("Error: " + io );

		} catch ( java.net.UnknownHostException o )  {

			System.out.println("Error: " + o );

		} catch ( java.rmi.RemoteException eo ) {
		
			System.out.println("Error: " + eo);	

		} catch ( java.rmi.NotBoundException io ) {

			System.out.println("Error: " + io);	
		}
		
		javax.swing.JOptionPane.showMessageDialog ( null, "El servidor RMI GestorRMI ha estat aturat", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE );
		servidorRmiIniciat = false;
		
    }
     
	/**
	*	Aquest mètode s'executa quan es fa clic en el botó de Inicia el servei de RMI
	*/
    private void botoIniciaActionPerformed(java.awt.event.ActionEvent evt) {
	
        if ( comprobaCamps()) {
            
            try   {
                     //String ipMysqlHost = this.textIpMySQL.getText();
                     //String bbddMysql = this.textBBDD.getText();
                     //String usuariMysql = this.textUsuariMySQL.getText();
                     //String passwdMysql = new String(this.textContrasenya.getPassword());                     
		     //this.gestorBBDD = new gestorBBDD ( ipMysqlHost , bbddMysql, usuariMysql, passwdMysql );

		if ( servidorRmiIniciat == false ) {
                                                        
		     Gestor mir = new Gestor( this.pathP12Gestor.getText(), new String(this.textContrasenyaGestor.getPassword()));
    		     String a = new String ( "//" + java.net.InetAddress.getLocalHost().getHostAddress() +  ":" + textPortRMI.getText() + "/GestorRMI");
		     java.rmi.Naming.rebind( a , mir);
                     servidorRmiIniciat = true;

		} else {

			javax.swing.JOptionPane.showMessageDialog ( null, "El servidor RMI GestorRMI ja està iniciat!", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE );

		}
	

	   } catch ( java.rmi.UnexpectedException eio ) {

			System.out.println("Error en RMI: " + eio );
			eio.printStackTrace();
			System.exit ( -1 );	

	   } catch (Exception e)    {  

			System.out.println("Error en main rmi" + e );  
			e.printStackTrace();
			System.exit ( -1 );
	   }
            
        }
    }

    private boolean comprobaCamps () {
        
        /*
        if (textIpMySQL.getText().compareTo("") == 0) {
            
            javax.swing.JOptionPane.showMessageDialog(null, "Error: Heu d'omplir el camp amb la IP del servidor MySQL", "Error", JOptionPane.ERROR_MESSAGE);
            textIpMySQL.requestFocus();
            return false;
            
        }
        
        if (textUsuariMySQL.getText().compareTo("") == 0) {
            
            javax.swing.JOptionPane.showMessageDialog ( null, "Error: Heu d'omplir el camp amb l'usuari del servidor MySQL", "Error", JOptionPane.ERROR_MESSAGE);
            textUsuariMySQL.requestFocus();
            return false;
        }
        
        String passwordMysql = new String ( textContrasenya.getPassword () );        
        if ( passwordMysql.compareTo("") == 0) {
            
            javax.swing.JOptionPane.showMessageDialog ( null, "Error: Heu d'omplir el camp amb la contrasenya del servidor MySQL", "Error", JOptionPane.ERROR_MESSAGE);
            textUsuariMySQL.requestFocus();
            return false;
        }
         */
        
        if (textPortRMI.getText().compareTo("") == 0) {
            
            javax.swing.JOptionPane.showMessageDialog ( null, "Error: Heu d'omplir el port amb el servidor RMI", "Error", JOptionPane.ERROR_MESSAGE);
            textPortRMI.requestFocus();            
            return false;
        }
        
        if (pathP12Gestor.getText().compareTo("") == 0) {
            javax.swing.JOptionPane.showMessageDialog ( null, "Error: Heu d'omplir el nom d'usuari del Gestor", "Error", JOptionPane.ERROR_MESSAGE);
            pathP12Gestor.requestFocus();
            return false;
        }
        
        
        String passwordGestor = new String( textContrasenyaGestor.getPassword() );
        if (passwordGestor.compareTo("") == 0) {
            javax.swing.JOptionPane.showMessageDialog ( null, "Error: Heu d'omplir la contrasenya del Gestor", "Error", JOptionPane.ERROR_MESSAGE);
            textContrasenyaGestor.requestFocus();
            return false;
        }
        
        return true;
    }
    
    
    private void botoSurtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoSurtActionPerformed

	if ( this.servidorRmiIniciat == true ) {

		this.aturaServeiRmi();

	}

        System.exit(-1);
    }//GEN-LAST:event_botoSurtActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pfcGuiGestor().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoAfegeixPac;
    private javax.swing.JButton botoAfegeixProf;
    private javax.swing.JButton botoAtura;
    private javax.swing.JButton botoCercaP12Gestor;
    private javax.swing.JButton botoInicia;
    private javax.swing.JButton botoSurt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField pathP12Gestor;
    private javax.swing.JPasswordField textContrasenyaGestor;
    private javax.swing.JTextField textPortRMI;
    // End of variables declaration//GEN-END:variables
    private gestorBBDD gestorBBDD;
    private boolean servidorRmiIniciat;
    private final static long serialVersionUID = 42L;
}
