/*
 * pfcGuiGestorNewPacient.java
 *
 * Created on 4 / gener / 2008, 16:17
 */

/**
 *
 * @author  Gerard Farràs i Ballabriga <gfarrasb@uoc.edu>
 */
public class pfcGuiGestorNewPacient extends javax.swing.JFrame {
    
    private gestorBBDD gestorBBDD;
    private pfcGuiGestor pfcGuiGestor;
    private final static long serialVersionUID = 42L;
    
    
    /** Creates new form pfcGuiGestorNewPacient */
    public pfcGuiGestorNewPacient() {
        
        initComponents();
        this.centraFormulari();
        
    }
    
    public void estableixDades ( pfcGuiGestor a ) {
        this.pfcGuiGestor = a;
        
    }
    
    private void centraFormulari () {
        
        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        java.awt.Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;                
        setLocation(screenWidth / 4, screenHeight / 4);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        botoAfegeixPacient = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textCognom1 = new javax.swing.JTextField();
        textCognom2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textDni = new javax.swing.JTextField();
        textTIS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textMetge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textCertificat = new javax.swing.JTextField();
        botoCercaCertificat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        botoAfegeixPacient.setText("D'acord");
        botoAfegeixPacient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAfegeixPacientActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel\u00b7la");
	jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
		botoCancelaPerformed(evt);
            }
        });

        jLabel1.setText("Afegeix nou pacient en el sistema");

        jLabel2.setText("Nom:");

        jLabel3.setText("Cognoms:");

        jLabel4.setText("DNI:");

        jLabel5.setText("TIS:");

        jLabel6.setText("Metge:");

        jLabel7.setText("Certificat:");

        botoCercaCertificat.setText("Cerca");
        botoCercaCertificat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoCercaCertificatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botoAfegeixPacient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textMetge)
                            .addComponent(textTIS)
                            .addComponent(textDni)
                            .addComponent(textNom)
                            .addComponent(textCognom1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCognom2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCertificat, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botoCercaCertificat)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textCognom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCognom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textTIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textMetge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(botoCercaCertificat)
                    .addComponent(textCertificat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoAfegeixPacient)
                    .addComponent(jButton2))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoCercaCertificatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoCercaCertificatActionPerformed
// TODO add your handling code here:
        
        javax.swing.JFileChooser a = new javax.swing.JFileChooser();      
         a.setVisible(true);       
       
        int returnVal = a.showOpenDialog(this); 
        
        if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {                        
               
               textCertificat.setText( a.getSelectedFile().getAbsolutePath());                                 
            
        }
    }//GEN-LAST:event_botoCercaCertificatActionPerformed

   

    private void botoAfegeixPacientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoAfegeixPacientActionPerformed

	 try {

        String nom = textNom.getText();
        String cognom1 = textCognom1.getText();
        String cognom2 = textCognom2.getText();
        String dni = textDni.getText();
        String tis = textTIS.getText();
        String metge = textMetge.getText();
        
	    //Obtenim el certificat per a col·locar-lo a la base de dades     
            //java.io.FileInputStream fileInput = new java.io.FileInputStream(textCertificat.getText());
            //iaik.x509.X509Certificate x509 = new iaik.x509.X509Certificate(fileInput);
            //String a =  new String (x509.toByteArray());             
        
	    String sqlInsertUser = "INSERT INTO `dtpacients` " +
                "( `nhc` , `dni` , `tis` , `nss` , `nom` , `cognom1` , `cognom2` , `correue` , `telf` , `direccio` , `codipostal` , `poblacio` , `metgeassignat` , `datanaixement` , `sexe` )" +
                "VALUES ('', '" + dni + "', '" + tis + "', NULL , '" + nom + "', '" + cognom1 + "', '" + cognom2 + "', '', '', '', '', '', '" +metge + "', '', 'H');";
        

	//String sqlInsertCert = "INSERT INTO `dtcertificats` ( `idusuari` , `certificat` ) VALUES ('', '" + a + "')";
	System.out.println("SQL --> " + sqlInsertUser );
	//System.out.println("SQL --> " + sqlInsertCert );
        //gestorBBDD gestorBBDD = new gestorBBDD ();
        //gestorBBDD.executaCanvisSQL ( sqlInsertUser );  
	javax.swing.JOptionPane.showMessageDialog ( null, "Funcionalitat NO implementada! Disculpeu les molesties!", 
						    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
		

	 } catch (Exception e ) { 
            System.out.println("Error: " + e);
        }
        
        
    }

	 private void botoCancelaPerformed(java.awt.event.ActionEvent evt) {        
		this.setVisible(false);        
	}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pfcGuiGestorNewPacient().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoAfegeixPacient;
    private javax.swing.JButton botoCercaCertificat;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textCertificat;
    private javax.swing.JTextField textCognom1;
    private javax.swing.JTextField textCognom2;
    private javax.swing.JTextField textDni;
    private javax.swing.JTextField textMetge;
    private javax.swing.JTextField textNom;
    private javax.swing.JTextField textTIS;
    // End of variables declaration//GEN-END:variables
    
}
