/*
 * pfcGuiLogin.java
 *
 * Created on 19 / novembre / 2007, 16:47
 */

/**
 *
 * @author  Gerard Farràs i Ballabriga <gfarrasb@uoc.edu>
 */
public class pfcGuiLogin extends javax.swing.JFrame {
    
    /** Constructor pfcGuiLogin */
    public pfcGuiLogin() {
        
        initComponents();   
        centraFormulari();
        
    }
    
    /**
     *Aquest mètode centra el formulari a la pantalla d'usuari.
     */    
    void centraFormulari() {
        
        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        java.awt.Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width; 
        setLocation(screenWidth / 4, screenHeight / 4);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        textUsuari = new javax.swing.JTextField();
        textPortRMI = new javax.swing.JTextField();
        botoOK = new javax.swing.JButton();
        botoCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textContrasenya = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        textIpRMI = new javax.swing.JTextField();
        botoCercap12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("pfc-Historials - Login");
        setAlwaysOnTop(true);
        //textUsuari.setText("25013981");

        botoOK.setText("D'acord");
        botoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoOKActionPerformed(evt);
            }
        });

        botoCancel.setText("Cancel\u00b7la");
        botoCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Fitxer p12:");

        jLabel2.setText("Contrasenya:");

        jLabel3.setText("RMI port:");

        //textContrasenya.setText("uoc0506");

        jLabel4.setText("IP RMI:");

        textIpRMI.setText("127.0.0.1");

        botoCercap12.setText("Cerca");
        botoCercap12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoCercap12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(botoOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(botoCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPortRMI, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(textUsuari, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(textContrasenya, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(textIpRMI, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botoCercap12)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botoCercap12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textIpRMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textPortRMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoOK)
                    .addComponent(botoCancel))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Aquest mètode obre un JFileChooser per a que l'usuari pugui
     * escollir un fitxer P12 per a autenticar-se en el sistema.
     */
    private void botoCercap12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoCercap12ActionPerformed
       
        javax.swing.JFileChooser a = new javax.swing.JFileChooser();      
        a.setVisible(true);         
        
       
        int returnVal = a.showOpenDialog(this);        
    
        if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {            
            
            textUsuari.setText( a.getSelectedFile().getAbsolutePath());
            this.nomUsuari = a.getSelectedFile().getName().substring(0, a.getSelectedFile().getName().indexOf("."));                       
            
        }
        
    }//GEN-LAST:event_botoCercap12ActionPerformed

    /**
     * Aquest mètode validarà les dades introduïdes amb el gestor.
     *
     * D'altra banda, si l'usuari introduït és un pacient, li apareixerà la interfície per a pacients.
     * Si es tracta en canvi d'un metge, li apareixerà la interfície adequada.
     *
     * 
     */
    private void botoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoOKActionPerformed
        
        String pathP12 = textUsuari.getText();        
        String contrasenya = new String(textContrasenya.getPassword()) ;
        String ipRMI = textIpRMI.getText();
        String portRMI = textPortRMI.getText ();
        
        if (nomUsuari.compareTo("") == 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Escriviu un nom d'usuari", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            textUsuari.requestFocus();
            return;
            
        }
        
        if (contrasenya.compareTo("") == 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Escriviu una contrasenya", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            //contrasenya.requestFocus();
            textContrasenya.requestFocus();
            return;
        }   
        
        if (ipRMI.compareTo("") == 0 ) {
            javax.swing.JOptionPane.showMessageDialog(null, "Escriviu la direcció IP del Gestor", "Error", javax.swing.JOptionPane.ERROR);
            textIpRMI.requestFocus();
        }
        
        if (portRMI.compareTo("") == 0 ) {
            javax.swing.JOptionPane.showMessageDialog(null, "Escriviu el port RMI", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            textPortRMI.requestFocus();
        }       
       
        
        
        try {
        
            GestorInterRemot gestor = (GestorInterRemot)java.rmi.Naming.lookup("//" + ipRMI + ":" + portRMI + "/GestorRMI");
              
            AutenticaUsuari a = new AutenticaUsuari ( nomUsuari, contrasenya , pathP12, gestor );
            boolean autentica = a.validaUsuari();        
        
        if (autentica) {           
                
                Pacient pacient = new Pacient ( nomUsuari, contrasenya, pathP12 );                
            
                if ( pacient.somMetge()) {
                    
                    pfcHistorialGuiMetge pfcHistorialGuiMetgeObj = new pfcHistorialGuiMetge();
                    pfcHistorialGuiMetgeObj.estableixDades ( nomUsuari, contrasenya, pathP12, gestor );
                    pfcHistorialGuiMetgeObj.setVisible ( true );
                    this.setVisible ( false );
                    
                } else {
                    
                    pfcHistorialGuiPacient pfcHistorialGuiPacientObj = new pfcHistorialGuiPacient();
                    pfcHistorialGuiPacientObj.estableixDades ( nomUsuari, contrasenya, pathP12, gestor );
                    pfcHistorialGuiPacientObj.setVisible ( true );
                    this.setVisible ( false );
                    
                    
                }
        } else {
            
            javax.swing.JOptionPane.showMessageDialog(null, "Error en la connexió", "Error d'usuari/contrasenya. Intenteu-ho altra vegada", javax.swing.JOptionPane.WARNING_MESSAGE);
        
        }
            
              }   catch (java.rmi.ConnectException o) {

			javax.swing.JOptionPane.showMessageDialog(null, "Error en la connexió RMI", 
									"Error en la connexió RMI",
									javax.swing.JOptionPane.ERROR_MESSAGE);
			System.exit(-1);

		 }   catch (Exception e)     {

			       e.printStackTrace();
            }
    }//GEN-LAST:event_botoOKActionPerformed

    /**
     *Aquest mètode aborta simplement el programa.
     */
    private void botoCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botoCancelActionPerformed
    
    /**
     * @param args No hi ha arguments.
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pfcGuiLogin().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoCancel;
    private javax.swing.JButton botoCercap12;
    private javax.swing.JButton botoOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField textContrasenya;
    private javax.swing.JTextField textIpRMI;
    private javax.swing.JTextField textPortRMI;
    private javax.swing.JTextField textUsuari;
    // End of variables declaration//GEN-END:variables
    private String nomUsuari;
    private final static long serialVersionUID = 42L;
}
