/*
 * pfcGuiLlistaPacients.java
 *
 * Created on 16 / novembre / 2007, 19:55
 */

/**
 *
 * @author  Gerard Farràs i Ballabriga <gfarrasb@uoc.edu>
 */
public class pfcGuiLlistaPacients extends javax.swing.JDialog {    
    
    private String ncolMetge;
    private String contrasenyaMetge;
    private String pathP12Metge;
    private GestorInterRemot gestor;
    private Metge metge;
    private pfcHistorialGuiMetge pfcHistorialGuiMetge;
    private final static long serialVersionUID = 42L;
    
    /** Creates new form pfcGuiLlistaPacients */
    public pfcGuiLlistaPacients() {        
        
        this.llistaPacientsModel = new javax.swing.DefaultListModel();
        initComponents(); 
        centraFormulari();            
        
    }
    
    void centraFormulari() {
        
        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        java.awt.Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;       
        setLocation(screenWidth / 4, screenHeight / 4);
        
    }
    
      //public void estableixDades ( String )
    public void estableixDades (String idMetge, String contrasenyaMetge, String pathP12Metge, GestorInterRemot gestor, pfcHistorialGuiMetge pfcHistorialGuiMetge ) {
        
        this.ncolMetge = idMetge;
        this.contrasenyaMetge = contrasenyaMetge;
        this.pathP12Metge = pathP12Metge;
        this.metge = new Metge ( this.ncolMetge, this.contrasenyaMetge, this.pathP12Metge );
        this.gestor = gestor;        
        this.pfcHistorialGuiMetge = pfcHistorialGuiMetge;
        
        estableixLlistatPacientsModel();
        
    }    
    
    
    public void estableixLlistatPacientsModel () {        
     
        
         try {
             
             org.jdom.Document a = metge.procedure1();
             org.jdom.Document b = gestor.procedure2(a);
             org.jdom.Document c = metge.pas3( b , "Llista_pacients");             
             boolean autentificacio = gestor.pas4 ( c );                        

             if (autentificacio) {
                                
                     org.jdom.Document llistatPacients = gestor.procedure5(this.ncolMetge);

                     java.util.Vector<String> vectorLlistatPacients;
                     vectorLlistatPacients = metge.procedure6(llistatPacients);
                    
                     for(int i=0;i<vectorLlistatPacients.size();i++) {                         
                         //llistaPacientsModel.addElement( (String)vectorLlistatPacients.get(i));
			llistaPacientsModel.addElement( vectorLlistatPacients.get(i));                                                  
                     } 
                     
             }                                         
                     
                                                                         
            }   catch (Exception e)     {

                               e.printStackTrace();
            }
    }
    
   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        llistaPacients = new javax.swing.JList();
        botoOK = new javax.swing.JButton();
        botoCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("pfcHistorials - Llistat de pacients assignats al metge");
        setAlwaysOnTop(true);
        llistaPacients.setModel(this.llistaPacientsModel);
        jScrollPane1.setViewportView(llistaPacients);

        botoOK.setText("D'acord");
        botoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoOKActionPerformed(evt);
            }
        });

        botoCancela.setText("Cancel\u00b7la");
        botoCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botoOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(botoCancela)
                        .addGap(144, 144, 144))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoCancela)
                    .addComponent(botoOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoCancelaActionPerformed
// TODO add your handling code here:
        this.setVisible ( false);
    }//GEN-LAST:event_botoCancelaActionPerformed

    private void botoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoOKActionPerformed
// TODO add your handling code here:
        
        String nomSeleccionat = (String)llistaPacients.getSelectedValue ();
        this.pfcHistorialGuiMetge.estableixPacient ( obteNHC(nomSeleccionat) );
        this.pfcHistorialGuiMetge.consultaHistorial ( obteNHC( nomSeleccionat) );
        this.setVisible ( false );        
        
    }//GEN-LAST:event_botoOKActionPerformed
    
    private String obteNHC (String nomPacient ) {
        return new String ( nomPacient.substring ( nomPacient.indexOf("(") + 1 , nomPacient.indexOf(")")));
    }
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoCancela;
    private javax.swing.JButton botoOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList llistaPacients;
    // End of variables declaration//GEN-END:variables
    
    private javax.swing.DefaultListModel llistaPacientsModel;
}
